name: DockerBuild
on:
  push:
    branches: 
    - master
jobs:
  webpack:
    name: Webpack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node_version: '13.x'
    - run: npm i yarn -g && yarn
    - run: yarn add webpack webpack-cli -D
    - run: ./node_modules/.bin/webpack --config webpack.config.js
    - if: success()
      uses: actions/upload-artifact@v1
      with:
        name: judger.js
        path: dist/judger.js
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: webpack
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: judger.js
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hydrooj/judger:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
  slim:
    name: BuildSlim
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hydrooj/judger:slim
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: slim.Dockerfile
  default:
    name: BuildDefault
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hydrooj/judger:default
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: default.Dockerfile
