name: DockerBuild
on:
  push:
    branches: 
    - master
jobs:
  ExecutorServer:
    name: Build ExecutorServer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run: |
        git clone https://github.com/criyle/go-judge.git
        cd go-judge
        go mod download
        go build -o executorserver ./cmd/executorserver
        go build -o cinit ./cmd/cinit
        go build -buildmode=c-shared -o executorserver.so ./cmd/executorserver
    - uses: actions/upload-artifact@master
      with:
        name: ExecutorServer
        path: go-judge/executorserver
    - uses: actions/upload-artifact@master
      with:
        name: cinit
        path: go-judge/cinit
    - uses: actions/upload-artifact@master
      with:
        name: ExecutorServer.so
        path: go-judge/executorserver.so
  webpack:
    name: Webpack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node_version: '13.x'
    - run: |
        yarn
        yarn add webpack webpack-cli -D
        yarn run webpack
    - uses: actions/upload-artifact@v1
      with:
        name: judger.js
        path: dist/judger.js
  pkg:
    name: Package
    runs-on: ubuntu-latest
    needs: [ExecutorServer, webpack]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node_version: '13.x'
    - uses: actions/download-artifact@v1
      with:
        name: judger.js
        path: judger.js
    - uses: actions/download-artifact@v1
      with:
        name: ExecutorServer
        path: executorserver
    - run: |
        yarn add pkg -D
        yarn run pack
    - uses: actions/upload-artifact@v1
      with:
        name: Judger_linux_amd64
        path: hydrojudger-linux
    - uses: actions/upload-artifact@v1
      with:
        name: Judger_macos_amd64
        path: hydrojudger-macos
    - uses: actions/upload-artifact@v1
      with:
        name: Judger_win_amd64.exe
        path: hydrojudger-win.exe
  latest:
    name: BuildLatest
    runs-on: ubuntu-latest
    needs: pkg
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: Judger_linux_amd64
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hydrooj/judger:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile/Dockerfile
  alpine:
    name: BuildAlpine
    runs-on: ubuntu-latest
    needs: pkg
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: Judger_linux_amd64
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hydrooj/judger:alpine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile/alpine.Dockerfile
  slim:
    name: BuildSlim
    runs-on: ubuntu-latest
    needs: alpine
    steps:
    - uses: actions/checkout@v2
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hydrooj/judger:slim
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile/slim.Dockerfile
  default:
    name: BuildDefault
    runs-on: ubuntu-latest
    needs: latest
    steps:
    - uses: actions/checkout@v2
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hydrooj/judger:default
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile/default.Dockerfile
